-- ##################################
-- Module 14 - Delete the Project Setup (Snowflake side)
-- ##################################
-- The course's own scripts covered setup/pause but not full teardown -
-- this follows the same object names, dropped in reverse dependency
-- order. Run this BEFORE `terraform destroy` on the AWS side.

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

ALTER TASK IF EXISTS DEA_REAL_TIME_SCD1.RAW.EMPLOYEE_SCD1_TASK SUSPEND;
DROP TASK IF EXISTS DEA_REAL_TIME_SCD1.RAW.EMPLOYEE_SCD1_TASK;
DROP PROCEDURE IF EXISTS DEA_REAL_TIME_SCD1.RAW.EMPLOYEE_SCD1_SP();
DROP STREAM IF EXISTS DEA_REAL_TIME_SCD1.RAW.EMPLOYEE_STREAM;
DROP TABLE IF EXISTS DEA_REAL_TIME_SCD1.TRANSFORMED.EMPLOYEE_TRANSFORMED;
DROP PIPE IF EXISTS DEA_REAL_TIME_SCD1.RAW.EMPLOYEE_PIPE;
DROP TABLE IF EXISTS DEA_REAL_TIME_SCD1.RAW.EMPLOYEE_RAW;
DROP STAGE IF EXISTS DEA_REAL_TIME_SCD1.RAW.DEA_REAL_TIME_SCD1_STAGE;
DROP STORAGE INTEGRATION IF EXISTS DEA_REAL_TIME_SCD1_INTEGRATION;
DROP SCHEMA IF EXISTS DEA_REAL_TIME_SCD1.TRANSFORMED;
DROP SCHEMA IF EXISTS DEA_REAL_TIME_SCD1.RAW;
DROP DATABASE IF EXISTS DEA_REAL_TIME_SCD1;

-- Then, from terraform/: terraform destroy
